### ISSUE TITLE
Need URI in skos:narrower / skos:broader for IVOA-UAT

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/Vocabularies#19]
The current RDF version of the IVOA-flavour UAT has literals in the skos:narrower / skos:broader object part, instead of URIs. This breaks the processing of the vocabulary by other tools understanding RDF.

**Comment by msdemlei** [comment]
On Fri, Mar 01, 2024 at 09:12:38AM -0800, Baptiste Cecconi wrote:
> The current RDF version of the IVOA-flavour UAT has literals in the
> skos:narrower / skos:broader object part, instead of URIs. This
> breaks the processing of the vocabulary by other tools
> understanding RDF.

Yeah, this was a stupid bug.  I've just installed an IVOA UAT built
with convert.py as of PR #20.  Does that fix your problem?  If so,
would you approve the PR?

**Comment by BaptisteCecconi** [comment]
yes, it is fixed. I close this issue.
